### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by dan-pascu** [zoidboi/laritio#1]
There is a Laravel 8 version available? I get this message

Problem 1
    - Root composer.json requires techshark/laritio ^1.0 -> satisfiable by techshark/laritio[1.0].
    - techshark/laritio 1.0 requires laravel/framework 5.* -> found laravel/framework[v5.0.0, ..., v5.8.38] but it conflicts with your root composer.json require (^v8.61.0).

**Comment by zoidboi** [comment]
Hey @dan-pascu,

Sorry for the delay in response, I'll take a look at the package in the recent laravel version and update the requirements.

**Comment by zoidboi** [comment]
Fixed in PR: #2
