### ISSUE TITLE
Class 'ZoidBoi\Laritio\Providers\LaritioServiceProvider' not found  

### ISSUE THREAD

**Issue by husainmusa** [zoidboi/laritio#3]
Class 'ZoidBoi\Laritio\Providers\LaritioServiceProvider' not found

**Comment by zoidboi** [comment]
Hey @husainmusa ,

Im not seeing this issue on my end, could you please tell me how you installed the package and how you are trying to use it? Most common fixes are:
1: Running: `php artisan vendor:publish`
2: Running: `composer dump-autoload`

Let me know!

**Comment by husainmusa** [comment]
> composer

thanks for your reply..
here i have try to install by composer like

**Comment by husainmusa** [comment]
composer require zoidboi/laritio

**Comment by zoidboi** [comment]
@husainmusa Mmh I resynced the package with packagist just to be sure this wasn't the issue, could you try to require the package again the normal way? Without adding the repository manually? Thanks!

**Comment by husainmusa** [comment]
> composer require zoidboi/laritio

Thank you very much.... now it's working

**Comment by zoidboi** [comment]
Perfect, good luck with your project!
